version: '3'

services:
  database:
    image: mysql:latest
    container_name: database
    networks:
      - network_database
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    volumes:
      - /var/lib/docker/volumes/database_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    networks:
      - network_database
    ports:
      - "8080:8080"
    links:
      - database:db

  app:
    build: .
    container_name: app
    networks:
      - network_app
      - network_database
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/app
    command: php -S 0.0.0.0:8000 -t public

networks:
  network_app: 
    driver: bridge
    name: network_app
  network_database:
    driver: bridge
    name: network_database