DROP DATABASE IF EXISTS test;

CREATE DATABASE test
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE test;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    password CHAR(60) NOT NULL COMMENT "Bcrypt hash",
    created_at DATETIME NOT NULL DEFAULT NOW(),
    updated_at DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
    PRIMARY KEY (id),
    UNIQUE (email)
) ENGINE = InnoDB;